CREATE TABLE filme (
	id INT AUTO_INCREMENT PRIMARY KEY,
	titulo_original VARCHAR(150) NOT NULL,
	titulo_portugues VARCHAR(150) NULL,
	ano_lancamento INT NOT NULL,
	link VARCHAR(2048),
	opiniao ENUM(
		'Não posso opinar',
		'Não vi e não tenho interesse',
		'Não vi e tenho interesse em ver',
		'Vi e não gostei',
		'Vi e gostei'
	) NOT NULL DEFAULT 'Não posso opinar',
	UNIQUE KEY (titulo_original, ano_lancamento)
);

INSERT INTO filme (titulo_original, titulo_portugues, ano_lancamento) VALUES
('The Matrix', 'Matrix', 1999),
('Fight Club', 'Clube da Luta', 1999),
('Inception', 'A Origem', 2010),
('Memento', 'Amnésia', 2000),
('Predestination', 'O Predestinado', 2014), 
('The Shining', 'O Iluminado', 1980),
('Full Metal Jacket', 'Nascido para Matar', 1987),
('Se7en', 'Seven: Os Sete Crimes Capitais', 1995),
('Pulp Fiction', 'Pulp Fiction: Tempo de Violência', 1994), 
('Reservoir Dogs', 'Cães de Aluguel', 1992), 
('Once Upon a Time in Hollywood', 'Era uma vez em... Hollywood', 2019),
('Catch Me If You Can', 'Prenda-me Se For Capaz', 2002),
('Aliens', 'Aliens, O Resgate', 1986),
('Alien', 'Alien, O Oitavo Passageiro', 1979),
('Terminator 2: Judgment Day', 'O Exterminador do Futuro 2: O Julgamento Final', 1991),
('The Terminator', 'O Exterminador do Futuro', 1984);

INSERT INTO filme (titulo_original, titulo_portugues, ano_lancamento) VALUES
('Oppenheimer', 'Oppenheimer', 2023),
('Everything Everywhere All at Once', 'Tudo em Todo o Lugar ao Mesmo Tempo', 2022),
('CODA', 'No Ritmo do Coração', 2021),
('Nomadland', 'Nomadland', 2020),
('Parasite', 'Parasita', 2019),
('Green Book', 'Green Book: O Guia', 2018),
('The Shape of Water', 'A Forma da Água', 2017),
('Moonlight', 'Moonlight: Sob a Luz do Luar', 2016),
('Spotlight', 'Spotlight: Segredos Revelados', 2015),
('Birdman', 'Birdman ou (A Inesperada Virtude da Ignorância)', 2014),
('12 Years a Slave', '12 Anos de Escravidão', 2013),
('Argo', 'Argo', 2012),
('The Artist', 'O Artista', 2011),
('The King''s Speech', 'O Discurso do Rei', 2010),
('The Hurt Locker', 'Guerra ao Terror', 2009),
('Slumdog Millionaire', 'Quem Quer Ser um Milionário?', 2008),
('No Country for Old Men', 'Onde os Fracos Não Têm Vez', 2007),
('The Departed', 'Os Infiltrados', 2006),
('Crash', 'Crash: No Limite', 2005),
('Million Dollar Baby', 'Menina de Ouro', 2004),
('The Lord of the Rings: The Return of the King', 'O Senhor dos Anéis: O Retorno do Rei', 2003),
('Chicago', 'Chicago', 2002),
('A Beautiful Mind', 'Uma Mente Brilhante', 2001),
('Gladiator', 'Gladiador', 2000),
('American Beauty', 'Beleza Americana', 1999),
('Shakespeare in Love', 'Shakespeare Apaixonado', 1998),
('Titanic', 'Titanic', 1997),
('The English Patient', 'O Paciente Inglês', 1996),
('Braveheart', 'Coração Valente', 1995),
('Forrest Gump', 'Forrest Gump: O Contador de Histórias', 1994),
('Schindler''s List', 'A Lista de Schindler', 1993),
('Unforgiven', 'Os Imperdoáveis', 1992),
('The Silence of the Lambs', 'O Silêncio dos Inocentes', 1991),
('Dances with Wolves', 'Dança com Lobos', 1990);

INSERT INTO filme (titulo_original, titulo_portugues, ano_lancamento) VALUES
('Insomnia', 'Insônia', 2002),
('Batman Begins', 'Batman Begins', 2005),
('The Prestige', 'O Grande Truque', 2006),
('The Dark Knight', 'Batman: O Cavaleiro das Trevas', 2008),
('The Dark Knight Rises', 'Batman: O Cavaleiro das Trevas Ressurge', 2012),
('Interstellar', 'Interestelar', 2014),
('Dunkirk', 'Dunkirk', 2017),
('Tenet', 'Tenet', 2020),
('Jackie Brown', 'Jackie Brown', 1997),
('Kill Bill: Vol. 1', 'Kill Bill: Volume 1', 2003),
('Kill Bill: Vol. 2', 'Kill Bill: Volume 2', 2004),
('Death Proof', 'À Prova de Morte', 2007),
('Inglourious Basterds', 'Bastardos Inglórios', 2009),
('Django Unchained', 'Django Livre', 2012),
('The Hateful Eight', 'Os Oito Odiados', 2015),
('Taxi Driver', 'Taxi Driver - Motorista de Táxi', 1976),
('Raging Bull', 'Touro Indomável', 1980),
('The King of Comedy', 'O Rei da Comédia', 1982),
('After Hours', 'Depois de Horas', 1985),
('The Color of Money', 'A Cor do Dinheiro', 1986),
('The Last Temptation of Christ', 'A Última Tentação de Cristo', 1988),
('Goodfellas', 'Os Bons Companheiros', 1990),
('Cape Fear', 'Cabo do Medo', 1991),
('The Age of Innocence', 'A Época da Inocência', 1993),
('Casino', 'Cassino', 1995),
('Kundun', 'Kundun', 1997),
('Bringing Out the Dead', 'Vivendo no Limite', 1999),
('Gangs of New York', 'Gangues de Nova York', 2002),
('The Aviator', 'O Aviador', 2004),
('Shutter Island', 'Ilha do Medo', 2010),
('Hugo', 'A Invenção de Hugo Cabret', 2011),
('The Wolf of Wall Street', 'O Lobo de Wall Street', 2013),
('Silence', 'Silêncio', 2016),
('The Irishman', 'O Irlandês', 2019),
('Killers of the Flower Moon', 'Assassinos da Lua das Flores', 2023),
('Star Wars: Episode IV – A New Hope', 'Star Wars: Uma Nova Esperança', 1977),
('Star Wars: Episode V – The Empire Strikes Back', 'Star Wars: O Império Contra-Ataca', 1980),
('Star Wars: Episode VI – Return of the Jedi', 'Star Wars: O Retorno de Jedi', 1983),
('Star Wars: Episode I – The Phantom Menace', 'Star Wars: A Ameaça Fantasma', 1999),
('Star Wars: Episode II – Attack of the Clones', 'Star Wars: Ataque dos Clones', 2002),
('Star Wars: Episode III – Revenge of the Sith', 'Star Wars: A Vingança dos Sith', 2005),
('Star Wars: Episode VII – The Force Awakens', 'Star Wars: O Despertar da Força', 2015),
('Rogue One: A Star Wars Story', 'Rogue One: Uma História Star Wars', 2016),
('Star Wars: Episode VIII – The Last Jedi', 'Star Wars: Os Últimos Jedi', 2017),
('Solo: A Star Wars Story', 'Han Solo: Uma História Star Wars', 2018),
('Star Wars: Episode IX – The Rise of Skywalker', 'Star Wars: A Ascensão Skywalker', 2019),
('Ace Ventura: Pet Detective', 'Ace Ventura: Um Detetive Diferente', 1994),
('The Mask', 'O Máskara', 1994),
('Dumb and Dumber', 'Debi & Lóide: Dois Idiotas em Apuros', 1994),
('Batman Forever', 'Batman Eternamente', 1995),
('The Cable Guy', 'O Pentelho', 1996),
('Liar Liar', 'O Mentiroso', 1997),
('The Truman Show', 'O Show de Truman', 1998),
('Man on the Moon', 'O Mundo de Andy', 1999),
('How the Grinch Stole Christmas', 'O Grinch', 2000),
('Bruce Almighty', 'Todo Poderoso', 2003),
('Eternal Sunshine of the Spotless Mind', 'Brilho Eterno de uma Mente Sem Lembranças', 2004),
('A Series of Unfortunate Events', 'Desventuras em Série', 2004),
('Yes Man', 'Sim Senhor', 2008),
('When Harry Met Sally...', 'Harry e Sally - Feitos Um para o Outro', 1989),
('Pretty Woman', 'Uma Linda Mulher', 1990),
('Sleepless in Seattle', 'Sintonia de Amor', 1993),
('Notting Hill', 'Um Lugar Chamado Notting Hill', 1999),
('10 Things I Hate About You', '10 Coisas Que Eu Odeio em Você', 1999),
('Legally Blonde', 'Legalmente Loira', 2001),
('Sweet Home Alabama', 'Doce Lar', 2002),
('Love Actually', 'Simplesmente Amor', 2003),
('50 First Dates', 'Como Se Fosse A Primeira Vez', 2004),
('The Proposal', 'A Proposta', 2009),
('Crazy, Stupid, Love.', 'Amor a Toda Prova', 2011),
('La La Land', 'La La Land: Cantando Estações', 2016);